### ISSUE TITLE
Rollback to originally imported transcript

### ISSUE THREAD

**Issue by solace** [pietrop/digital-paper-edit-electron#83]
Hi,

I have an issue with the editor that I'm still trying to debug before I can submit bug report. My problem is that sometimes clipboard text ends up replacing parts of the transcript repeatedly, some timestamps seem to shift out of order and any attempts to remove them just bumps everything else out even further, and various other seemingly insane side-effects. I lost about 4 hours of work because I hadn't noticed it happened in a long transcript and only realised after I saved, exited, and reopened the transcript that Things Were Not Right.

Is there a way to rollback to the originally imported transcript, or do I have to create a new transcript to transcribe again?

Alternatively, is there a way to access the raw file? I can take copies to manually restore, and move some of the mis-located timestamps if it happens again.

Thanks

**Comment by pietrop** [comment]
Hi @solace 
Sorry to hear about the issue. 

Questions:
-  Which version of autoEdit.io are you on?
- What operating system are you on?( Mac, Windows, PC) and ideally which version?
- Which Speech to text service did you use?

I am not sure about the clipboard you mentioned, but we had an issue with the editor that sounds similar, but it should have been fixed in the latest release.

If you are not already on the latest release, I'd suggest to download the [latest release](https://github.com/pietrop/digital-paper-edit-electron/releases), currently [`1.6.5-alpha.0`](https://github.com/pietrop/digital-paper-edit-electron/releases/tag/1.6.5-alpha.0),  and see if the issue persist there.


>clipboard text ends up replacing parts of the transcript repeatedly

I am not sure what this means. Do you mean that text that is copied into your computer's clipboard from somewhere else or other parts of the editor, appears in the editor without you pasting it there?

>Is there a way to rollback to the originally imported transcript, or do I have to create a new transcript to transcribe again?

Currently there is no way to rollback to the original transcript. 

If you have a session still open `cm` +`z` will roll back one change at a time (but only works if you haven't closed the app)


>Alternatively, is there a way to access the raw file? I can take copies to manually restore, and move some of the mis-located timestamps if it happens again.

On a mac you'd go to `Finder` --> `Go` (in the top bar) --> `Go To Folder...`

```
~/Library/Application\ Support/digital-paper-edit-electron/db
```

And the `transcripts.json` contains all the transcripts. You might want to use something like [visual studio code](https://code.visualstudio.com/) of equivalent to format the `json` and make it more readable. To find the bits you want to change. You can modify this as a last resort, but I don't recommend it as if you add an error in the json formatting it might load back into the app, and then you'd have to troubleshoot that.

**Comment by solace** [comment]
Hello @pietrop!

* 1.6.5-alpha.0
* OSX Catalina 10.15.7
* AssemblyAI

> > clipboard text ends up replacing parts of the transcript repeatedly

<img width="604" alt="Screen Shot 2021-08-22 at 10 56 36 am" src="https://user-images.githubusercontent.com/374583/130340416-68dcb8e5-1594-4f0d-a70a-35289a67b281.png">

In fairness, I'm just speculating that it yanked this from my clipboard, but I know I had "Oh my goodness" in my clipboard at some point and it was a single sentence speaker entry. I can't imagine why else it would have decided to repeat this one fragment over about 1 minute / 3 speaker items / 4 page scrolls of transcript. :/ 

> And the `transcripts.json` contains all the transcripts.

Yes, `cmd+z` only took me so far, but thank you! I can work with taking backups and modifying the json file if things go pear-shaped again. At least I won't have to keep blowing through AssemblyAI quota to start over. I have linters and things to avoid syntax errors so no problem there.
